name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          extra_args: --all-files --hook-stage manual
      - name: Install package
         run: python -m pip install -e .[precom]
      - uses: pre-commit/action@v3.0.0

  tests:
   runs-on: ubuntu-latest
   strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.8"
          - "3.12"
  name: Check Python ${{ matrix.python-version }}
  steps:
    - uses: actions/checkout@v3

    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install package
      run: python -m pip install -e .[test]

    - name: Test package
      run: python -m pytest
